### ISSUE TITLE
Idea - Language Server

### ISSUE THREAD

**Issue by PowerUser64** [grame-cncm/faustideas#10]
A [language server](https://en.wikipedia.org/wiki/Language_Server_Protocol), sometimes called an LSP, is a code analysis tool that allows programming environments to get information about projects. This lets them display information like code completions, inline errors, locations of function definitions, reference official documentation, and more. Many programming languages have their own language server (see https://langserver.org/ for a list), but it seems that Faust doesn't. If there was a Faust language server, it would make it easier to write Faust code using any IDE that supports LSP. This would make it easier for beginners to get started writing Faust using programming tools they're already familiar with, and it would make it easier for experts to navigate large codebases.

Since there is no Faust language server yet, I think writing it down here would be a really good idea.

**Comment by PowerUser64** [comment]
It's also worth noting that we already have a Faust tree-sitter grammar (https://github.com/khiner/tree-sitter-faust), which could be helpful in doing any parsing required for a language server.

**Comment by sletz** [comment]
Added here https://github.com/grame-cncm/faustideas?tab=readme-ov-file#faust-language-server, thanks.
